import os
os.chdir(os.path.expanduser('~/proc_track'))
src = open('replay_harness.py').read()
src = src.replace(r'Vote explanation\(s\) filed[^.]*', r'Vote explanation[^.]*')
src = src.replace(r'[^.]*excused, granted unanimous consent to vote[^.]*', r'[^.]*(excused|absent), granted unanimous consent to vote[^.]*')
src = src.replace(r'Without recommendation as to (passage|adoption)', r'Without recommendation')
src = src.replace(r'Vote reconsideration carried', r'Vote reconsideration (carried|failed)')
src = src.replace(r'Recommendation:\s+Do pass', r'Recomme[nd]dation:\s+Do pass')
src = src.replace(r'Recommendation:\s+Do adopt', r'Recomme[nd]dation:\s+Do adopt')
src = src.replace(r'Recommendation:\s+Be adopted', r'Recomme[nd]dation:\s+Be adopted')
src = src.replace('("effective_date",', '("filed_without_signature", r"Filed without Governor.s signature", "enacted", {}),\n    ("effective_date",')
src = src.replace('("in_committee_adjournment",   r"In committee upon adjournment",    "committee", {}),', '("in_committee_adjournment",   r"In committee upon adjournment",    "committee", {}),\n    ("in_conference_adjournment",   r"In conference committee upon adjournment", "committee", {"conference": True}),')
src = src.replace('("informational_meeting",      r"Informational Meeting held",       None, {}),', '("informational_meeting",      r"Informational Meeting held",       None, {}),\n    ("event_scheduled",             r"(Public Hearing|Work Session|Informational Meeting) [Ss]cheduled", None, {}),')
src = src.replace('("motion_carried_generic",', '("motion_postpone",            r"Motion to pos[tp]one[^.]*",         None, {"postponed": True}),\n    ("motion_carried_generic",')
src = src.replace('("subsequent_referral_resc",', '("subsequent_referral_denied", r"[Rr]escission of the subsequent referral denied[^.]*", None, {}),\n    ("subsequent_referral_resc",')
src = src.replace('"third_reading": {"passed", "adopted", "failed", "committee", "third_reading"},', '"third_reading": {"passed", "adopted", "failed", "committee", "third_reading", "second_reading"},')
src = src.replace('"signed_by_presiding": {"signed_by_presiding", "enacted", "vetoed", "committee"},', '"signed_by_presiding": {"signed_by_presiding", "enacted", "vetoed", "committee"},\n    "enacted": {"vetoed", "veto_sustained"},')
open('replay_harness.py','w').write(src)
print('patched')
