"""Derive per-chamber transition graphs from what the corpus actually does,
and write them to schemas/<session>_chamber_flows.py.

    python scripts/derive_chamber_flows.py 2025R1

Why: a graph shared across chambers grants permission neither chamber uses.
On 2025R1 the declared shared graph was 64 edges applied to both chambers
(128 chamber-edges); the corpus only ever took 65. That unused half is where
false-accepts live — restricting to observed edges took adjacent-swap
rejection from 14.5% to 35.2% with completion unchanged at 100%.

CAUTION: this is learned from observation, so a legal-but-unobserved edge gets
rejected. Edges seen <= REVIEW_THRESHOLD times are printed for review, not
silently trusted. When you add a second session, MERGE the edge sets — never
overwrite, or you drop procedure the earlier session proved legal.
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import replay_harness as h  # noqa: E402
from scripts.bulk_replay import load  # noqa: E402

REVIEW_THRESHOLD = 2


def main(session):
    _, by = load(session)
    observed = collections.Counter()
    incomplete = 0
    for mid, mrows in by.items():
        item, halt, _ = h.replay(mid, mrows)
        if halt:
            incomplete += 1
        for _occurred, ch, frm, to, _rid in item.history:
            observed[(ch, frm, to)] += 1

    if incomplete:
        print(f"WARNING: {incomplete} measures did not complete; derive from a "
              f"100% run or you will bake in a truncated graph.\n")

    chambers = sorted({c for c, _, _ in observed})
    flows = {c: collections.defaultdict(set) for c in chambers}
    for (c, frm, to), _n in observed.items():
        flows[c][frm].add(to)

    declared = sum(len(v) for v in h.CHAMBER_FLOW.values())
    total_observed = sum(len(v) for f in flows.values() for v in f.values())
    print(f"declared (shared): {declared} edges x {len(chambers)} chambers = "
          f"{declared*len(chambers)} chamber-edges")
    print(f"observed:          {total_observed} chamber-edges "
          f"({100*total_observed/(declared*len(chambers)):.0f}% of granted permission used)")
    for c in chambers:
        others = set()
        for o in chambers:
            if o != c:
                others |= {(f, t) for (cc, f, t) in observed if cc == o}
        mine = {(f, t) for (cc, f, t) in observed if cc == c}
        only = sorted(mine - others, key=str)
        print(f"\n  {c}-only edges ({len(only)}): {only}")

    rare = sorted(((k, n) for k, n in observed.items() if n <= REVIEW_THRESHOLD),
                  key=lambda kv: kv[1])
    print(f"\n--- observed <= {REVIEW_THRESHOLD} times: {len(rare)} (REVIEW, do not auto-adopt) ---")
    for (c, frm, to), n in rare:
        print(f"{n:5}  {c}: {frm} -> {to}")

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "schemas", f"{session}_chamber_flows.py")
    with open(out, "w") as f:
        f.write(f'"""Derived from {session} — {total_observed} observed chamber-edges.\n'
                f'Generated by scripts/derive_chamber_flows.py. Merge, never overwrite.\n"""\n\n')
        f.write("CHAMBER_FLOWS = {\n")
        for c in chambers:
            f.write(f'    "{c}": {{\n')
            for frm in sorted(flows[c], key=str):
                tos = sorted(flows[c][frm])
                f.write(f"        {frm!r}: {set(tos)!r},\n")
            f.write("    },\n")
        f.write("}\n")
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "2025R1")
