"""Derived from 2023R1 — 60 observed chamber-edges.
Generated by scripts/derive_chamber_flows.py. Merge, never overwrite.
"""

CHAMBER_FLOWS = {
    "H": {
        None: {'introduced', 'adopted'},
        'adopted': {'signed_by_presiding'},
        'committee': {'committee', 'second_reading', 'third_reading', 'work_session', 'public_hearing'},
        'failed': {'passed'},
        'introduced': {'third_reading', 'committee'},
        'passed': {'passed', 'signed_by_presiding', 'committee'},
        'public_hearing': {'public_hearing', 'work_session', 'committee'},
        'second_reading': {'third_reading', 'committee'},
        'signed_by_presiding': {'enacted', 'committee', 'vetoed'},
        'third_reading': {'passed', 'failed', 'committee', 'second_reading', 'third_reading', 'adopted'},
        'vetoed': {'veto_sustained'},
        'work_session': {'public_hearing', 'work_session', 'committee'},
    },
    "S": {
        None: {'introduced', 'adopted'},
        'adopted': {'signed_by_presiding'},
        'committee': {'committee', 'second_reading', 'third_reading', 'work_session', 'public_hearing'},
        'failed': {'passed', 'committee'},
        'introduced': {'committee'},
        'passed': {'third_reading', 'passed', 'signed_by_presiding', 'committee'},
        'public_hearing': {'public_hearing', 'work_session', 'committee'},
        'second_reading': {'third_reading', 'committee'},
        'signed_by_presiding': {'enacted'},
        'third_reading': {'passed', 'failed', 'committee', 'third_reading', 'adopted'},
        'work_session': {'work_session', 'committee'},
    },
}
