"""Derived from 2025R1 — 65 observed chamber-edges.
Generated by scripts/derive_chamber_flows.py. Merge, never overwrite.
"""

CHAMBER_FLOWS = {
    "H": {
        None: {'introduced'},
        'adopted': {'signed_by_presiding'},
        'committee': {'public_hearing', 'second_reading', 'passed', 'signed_by_presiding', 'committee', 'work_session', 'third_reading'},
        'failed': {'passed'},
        'introduced': {'adopted', 'committee', 'third_reading'},
        'passed': {'signed_by_presiding', 'passed', 'tabled', 'committee'},
        'public_hearing': {'public_hearing', 'committee', 'work_session'},
        'second_reading': {'committee', 'third_reading'},
        'signed_by_presiding': {'vetoed', 'enacted'},
        'tabled': {'veto_sustained'},
        'third_reading': {'passed', 'failed', 'adopted', 'committee', 'third_reading'},
        'vetoed': {'veto_sustained', 'tabled'},
        'work_session': {'public_hearing', 'committee', 'work_session'},
    },
    "S": {
        None: {'introduced', 'adopted'},
        'adopted': {'signed_by_presiding'},
        'committee': {'public_hearing', 'second_reading', 'passed', 'committee', 'work_session'},
        'failed': {'committee', 'third_reading'},
        'introduced': {'committee'},
        'passed': {'veto_sustained', 'signed_by_presiding', 'passed', 'committee'},
        'public_hearing': {'public_hearing', 'committee', 'work_session'},
        'second_reading': {'committee', 'third_reading'},
        'signed_by_presiding': {'vetoed', 'enacted'},
        'third_reading': {'adopted', 'passed', 'failed', 'third_reading'},
        'vetoed': {'veto_sustained', 'passed'},
        'work_session': {'committee', 'work_session'},
    },
}
