"""Derived from 2025R1 — 65 observed chamber-edges.
Generated by scripts/derive_chamber_flows.py. Merge, never overwrite.
"""

CHAMBER_FLOWS = {
    "H": {
        None: {'introduced'},
        'adopted': {'signed_by_presiding'},
        'committee': {'work_session', 'third_reading', 'signed_by_presiding', 'public_hearing', 'second_reading', 'committee', 'passed'},
        'failed': {'passed'},
        'introduced': {'adopted', 'committee', 'third_reading'},
        'passed': {'signed_by_presiding', 'committee', 'tabled', 'passed'},
        'public_hearing': {'work_session', 'committee', 'public_hearing'},
        'second_reading': {'third_reading', 'committee'},
        'signed_by_presiding': {'vetoed', 'enacted'},
        'tabled': {'veto_sustained'},
        'third_reading': {'third_reading', 'failed', 'adopted', 'committee', 'passed'},
        'vetoed': {'veto_sustained', 'tabled'},
        'work_session': {'work_session', 'committee', 'public_hearing'},
    },
    "S": {
        None: {'adopted', 'introduced'},
        'adopted': {'signed_by_presiding'},
        'committee': {'work_session', 'public_hearing', 'second_reading', 'committee', 'passed'},
        'failed': {'third_reading', 'committee'},
        'introduced': {'committee'},
        'passed': {'signed_by_presiding', 'veto_sustained', 'committee', 'passed'},
        'public_hearing': {'work_session', 'committee', 'public_hearing'},
        'second_reading': {'third_reading', 'committee'},
        'signed_by_presiding': {'vetoed', 'enacted'},
        'third_reading': {'adopted', 'third_reading', 'failed', 'passed'},
        'vetoed': {'veto_sustained', 'passed'},
        'work_session': {'work_session', 'committee'},
    },
}
